apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graalkus-jit-hpda
  namespace: fugerit-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graalkus-jit
  minReplicas: 1
  maxReplicas: 1
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
        - type: Percent
          value: 50
          periodSeconds: 15
      selectPolicy: Min
      stabilizationWindowSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
        - type: Percent
          value: 50
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0
