# docker compose -f src/main/docker/docker-compose.yml up -d

# Define the services
services:
  graalkus-jit:
    image: fugeritorg/graalkus:latest
    container_name: graalkus-jit
    restart: always
    ports:
      - "8081:8080"
  graalkus-aot:
    image: fugeritorg/graalkus:latest-amd64native
    container_name: graalkus-aot
    restart: always
    ports:
      - "8082:8080"
  graalkus-aot-optimized:
    image: fugeritorg/graalkus:latest-amd64native-pgo
    container_name: graalkus-aot-optimized
    restart: always
    ports:
      - "8083:8080"
