# docker compose -f src/main/docker/docker-compose-mixed.yml up -d

networks:
  graalkus_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16

# Define the services
services:

  api-gateway-mixed:
    image: nginx:latest
    container_name: graalkus-api-mixed
    volumes:
      - ${PWD}/src/main/docker/nginx-mixed/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - graalkus_network
    ports:
      - "8088:80"


  graalkus-jit-mixed:
    image: fugeritorg/graalkus:latest
    container_name: graalkus-jit-mixed
    restart: always
    networks:
      - graalkus_network
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 128M
        reservations:
          cpus: 1.0
          memory: 64M

  graalkus-aot-mixed:
    image: fugeritorg/graalkus:latest-amd64native-pgo
    container_name: graalkus-aot-mixed
    restart: always
    networks:
      - graalkus_network
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 128M
        reservations:
          cpus: 1.0
          memory: 64M