# docker compose -f src/main/docker/docker-compose-mixed.yml up -d

networks:
  graalkus_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16

# Define the services
services:

  api-gateway-mixed:
    image: traefik:v2.5
    container_name: graalkus-api-mixed
    volumes:
      - ${PWD}/src/main/docker/traefik-mixed/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - graalkus_network
    ports:
      - "8088:80"
      - "8089:8080"

  graalkus-jit-mixed:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4
    container_name: graalkus-jit-mixed
    hostname: jit
    labels:
      - traefik.http.routers.jit.rule=Path(`/doc/example.pdf`)
    restart: always
    networks:
      - graalkus_network
    ports:
      - "8086:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 64M

  graalkus-aot-mixed:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4-native-pgo
    container_name: graalkus-aot-mixed
    hostname: aot
    labels:
      - traefik.http.routers.aot.rule=PathPrefix(`/doc`)
    restart: always
    networks:
      - graalkus_network
    ports:
      - "8087:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 64M
        reservations:
          cpus: '0.5'
          memory: 32M

  graalkus-jit-std:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4
    container_name: graalkus-jit-mixed-std
    hostname: jit-std
    restart: always
    networks:
      - graalkus_network
    ports:
      - "8085:8080"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 128M