# docker compose -f src/main/docker/docker-compose.yml up -d

# Define the services
services:
  graalkus-jit:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4
    container_name: graalkus-jit
    restart: always
    ports:
      - "8081:8080"
  graalkus-aot:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4-native
    container_name: graalkus-aot
    restart: always
    ports:
      - "8082:8080"
  graalkus-aot-optimized:
    # it is possible to pick more options from :
    # https://hub.docker.com/repository/docker/fugeritorg/graalkus/general
    # or build your own image locally.
    image: fugeritorg/graalkus:v1.3.4-native-pgo
    container_name: graalkus-aot-optimized
    restart: always
    ports:
      - "8083:8080"
