apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graalkus-aot-pg-hpda
  namespace: fugerit-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graalkus-aot-pgo
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
