kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config-cm
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entryPoints:
      web:
        address: :80
