kind: ConfigMap
apiVersion: v1
metadata:
  name: graalkus-api-mixed-krakend-cm
  namespace: fugerit-dev
data:
  krakend.json: |
      {
        "$schema": "https://www.krakend.io/schema/v3.json",
        "version": 3,
        "name": "graalkus-api-mixed-krakend",
        "port": 8080,
        "endpoints": [
          {
            "endpoint": "/doc/example.md",
            "output_encoding": "no-op",
            "backend": [
              {
                "host": ["http://graalkus-aot-pgo-service:80"],
                "url_pattern": "/doc/example.md"
              }
            ]
          },
          {
            "endpoint": "/doc/example.adoc",
            "output_encoding": "no-op",
            "backend": [
              {
                "host": ["http://graalkus-aot-pgo-service:80"],
                "url_pattern": "/doc/example.adoc"
              }
            ]
          },
          {
            "endpoint": "/doc/example.html",
            "output_encoding": "no-op",
            "backend": [
              {
                "host": ["http://graalkus-aot-pgo-service:80"],
                "url_pattern": "/doc/example.html"
              }
            ]
          },
          {
            "endpoint": "/doc/example.pdf",
            "output_encoding": "no-op",
            "backend": [
              {
                "host": ["http://graalkus-jit-service:80"],
                "url_pattern": "/doc/example.pdf"
              }
            ]
          }
        ]
      }