apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graalkus-aot-hpda
  namespace: fugerit-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graalkus-aot
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
