# CI with maven build and scan

name: CI deploy openshift AOT PGO

# note for this workflow two secrets are need to complete the OpenShift login :
#
# OPENSHIFT_TOKEN
# OPENSHIFT_SERVER
#
# NOTE: if those parameters are not valid, build will fail.

on:
  push:
    branches:
      - deploy-ocp-aot-pgo

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Echo ref name trigger
        run: echo ${{ github.ref_name }}
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@main
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven version
        run: mvn -v
        env:
          # Needed to get some information about the pull request, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install h2load
        run: sudo apt-get install nghttp2-client
      - name: Check h2load
        run: h2load --version
      - name: Install oc cli
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: 'latest'
      - name: Check oc cli
        run: oc version
      - name: Build instrumented
        run: 'mvn clean package -Dnative -Pinstrumented'
      - name: Run workload
        run: './src/main/script/bench-graph-h2-load.sh -m AOT'
      - name: Openshift Login
        run: 'oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}'
      - name: Build optimzed
        run: 'mvn clean package -Dnative -Poptimized -Dquarkus.openshift.deploy=true -Dquarkus.openshift.name=graalkus-aot-pgo'
